name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for stopping by. I Appreciate you taking the time to fill our your'' first issue'
        pr-message: 'Your have just made your first pull request to healthyR! Thank you'' .'
